version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: sudo ./run.sh
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report