version: 2
jobs:
  build:
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: 
          - emulator -avd circleci-android22 -no-audio -no-window:
          background: true
          parallel: true
      # wait for it to have booted
      - circle-android wait-for-boot
      # unlock the emulator screen
      - sleep 30
      - adb shell input keyevent 82
      # run tests  against the emulator.
      - katalon-execute.sh -browserType="Chrome" -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Search -browserType="Android""
      # copy the build outputs to artifacts
      - cp -r app/build/outputs $CIRCLE_ARTIFACTS
      # copy the test results to the test results directory.
          command: 
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report