version: 2
jobs:
  build:
    working_directory: ~/Katalon-Android
    docker:
      - image: katalonstudio/katalon
    steps:
      - checkout
      - run:
          name: Execute Katalon Studio
          command: cd ~/Katalon-Android && katalon-execute.sh -retry=0 -statusDelay=15 -testSuitePath="Test Suites/Search" -browserType="iphonesimul"
      - store-test_results:
          path: ./report
      - store-artifacts:
          path: ./report